---

fail_fast: false
minimum_pre_commit_version: 2.6.0

repos:
  -
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9  # frozen: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: templates/.*
      - id: mixed-line-ending
        args: [--fix=lf]
      #      - id: trailing-whitespace
      #- id: flake8

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 3420134c37197c21edffc7e6093b14ffae8402f2  # frozen: v1.81.0
    hooks:
      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_fmt
      - id: terraform_fmt

      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_validate
      - id: terraform_validate
        exclude: examples/.*

      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_docs
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yaml
          - --args=--lockfile=false

      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_providers_lock
      - id: terraform_providers_lock

      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_tflint
      - id: terraform_tflint
        exclude: 'examples/.*'
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl

      - id: terraform_tfsec
        args:
          - --args=--exclude-downloaded-modules
          - --args=--custom-check-dir=__GIT_WORKING_DIR__/.tfsec
        files: \.tf$
        exclude: \.terraform\/.*$
  - repo: local
    hooks:
      - id: restricted-filenames
        name: Check commits for unexpected file extensions
        entry: These files are prohibited and should be removed.
        language: fail
        files: '.*\.(taskcat_overrides.yml)'
